project:
  type: book
  output-dir: docs

book:
  title: "Introdução à Geoinformática"
  author: "Édipo H. Cremon"
  date: "03/10/2026"
  cover-image: fig/capa.png
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

lang: pt-BR

bibliography: references.bib
csl: abnt.csl

format:
  html:
    css: estilos.css
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


editor: visual

